<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Dapper" Version="2.1.72" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.6" />
        <PackageReference Include="Npgsql" Version="10.0.1" />
        <PackageReference Include="WolverineFx" Version="5.27.0" />
        <PackageReference Include="WolverineFx.Http" Version="5.27.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\CMA.Core\CMA.Core.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Content Include="..\CMA.Core\appsettings.Shared.json" Link="appsettings.Shared.json">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
      </Content>
      <Content Include="..\CMA.Core\appsettings.Development.Shared.json" Link="appsettings.Development.Shared.json">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
      </Content>
    </ItemGroup>

</Project>
