CREATE TABLE IF NOT EXISTS device
(
    id         SERIAL PRIMARY KEY,
    name       VARCHAR(255) NOT NULL,
    ip_address VARCHAR(45)  NOT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

